// @generated by protobuf-ts 2.9.3 with parameter output_javascript
// @generated from protobuf file "pbf/policy/api.proto" (package "policy", syntax proto3)
// tslint:disable
/**
 * @generated ServiceType for protobuf service policy.API
 */
export declare const API: any;
