// @generated by protobuf-ts 2.9.1 with parameter output_javascript
// @generated from protobuf file "pbf/wallet/update.proto" (package "wallet", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * UpdateI is the input for updating wallets. Solving the signature verification
 * challenge again for an existing wallet updates object.intern.last. That is,
 * refreshing the wallet's validity and its user's ownership claim.
 *
 *     {
 *         "object": [
 *             {
 *                 "intern": {
 *                     "wllt": "338912367"
 *                 },
 *                 "public": {
 *                     "mess": "...",
 *                     "pubk": "0x1234",
 *                     "sign": "0x2345"
 *                 }
 *             }
 *         ]
 *     }
 *
 * The message format is expected to be as shown below.
 *
 *     signing ownership of [    addr    ] at [  unix  ]
 *
 *     signing ownership of 0x7483••••ba5B at 1695326302
 *
 *
 * @generated from protobuf message wallet.UpdateI
 */
export interface UpdateI {
  /**
   * @generated from protobuf field: wallet.UpdateI_Filter filter = 100;
   */
  filter?: UpdateI_Filter;
  /**
   * @generated from protobuf field: repeated wallet.UpdateI_Object object = 200;
   */
  object: UpdateI_Object[];
}
/**
 * @generated from protobuf message wallet.UpdateI_Filter
 */
export interface UpdateI_Filter {}
/**
 * @generated from protobuf message wallet.UpdateI_Object
 */
export interface UpdateI_Object {
  /**
   * @generated from protobuf field: wallet.UpdateI_Object_Intern intern = 100;
   */
  intern?: UpdateI_Object_Intern;
  /**
   * @generated from protobuf field: wallet.UpdateI_Object_Public public = 200;
   */
  public?: UpdateI_Object_Public;
  /**
   * @generated from protobuf field: wallet.UpdateI_Object_Symbol symbol = 300;
   */
  symbol?: UpdateI_Object_Symbol;
  /**
   * @generated from protobuf field: repeated wallet.UpdateI_Object_Update update = 400;
   */
  update: UpdateI_Object_Update[];
}
/**
 * @generated from protobuf message wallet.UpdateI_Object_Intern
 */
export interface UpdateI_Object_Intern {
  /**
   * wllt is the ID of the wallet being updated.
   *
   * @generated from protobuf field: string wllt = 100;
   */
  wllt: string;
}
/**
 * @generated from protobuf message wallet.UpdateI_Object_Public
 */
export interface UpdateI_Object_Public {
  /**
   * mess is the message to sign. It is ephemeral and will not be stored in the
   * backend.
   *
   * @generated from protobuf field: string mess = 100;
   */
  mess: string;
  /**
   * pubk is the hex encoded public key expected to be recovered from the given
   * signature during the signature verification challenge. It is ephemeral and
   * will not be stored in the backend.
   *
   * @generated from protobuf field: string pubk = 200;
   */
  pubk: string;
  /**
   * sign is the signature of the signed message. It is ephemeral and will not
   * be stored in the backend.
   *
   * @generated from protobuf field: string sign = 300;
   */
  sign: string;
}
/**
 * @generated from protobuf message wallet.UpdateI_Object_Symbol
 */
export interface UpdateI_Object_Symbol {}
/**
 * @generated from protobuf message wallet.UpdateI_Object_Update
 */
export interface UpdateI_Object_Update {
  /**
   * @generated from protobuf field: optional string frm = 100;
   */
  frm?: string;
  /**
   * @generated from protobuf field: string ope = 200;
   */
  ope: string;
  /**
   * @generated from protobuf field: string pat = 300;
   */
  pat: string;
  /**
   * @generated from protobuf field: optional string val = 400;
   */
  val?: string;
}
/**
 * UpdateO is the output for updating wallets.
 *
 *     {
 *         "object": [
 *             {
 *                 "intern": {
 *                     "addr": {
 *                         "time": "1695326765"
 *                     },
 *                     "labl": {
 *                         "time": "1695326765"
 *                     },
 *                     "stts": "updated"
 *                 }
 *             }
 *         ]
 *     }
 *
 *
 * @generated from protobuf message wallet.UpdateO
 */
export interface UpdateO {
  /**
   * @generated from protobuf field: wallet.UpdateO_Filter filter = 100;
   */
  filter?: UpdateO_Filter;
  /**
   * @generated from protobuf field: repeated wallet.UpdateO_Object object = 200;
   */
  object: UpdateO_Object[];
}
/**
 * @generated from protobuf message wallet.UpdateO_Filter
 */
export interface UpdateO_Filter {}
/**
 * @generated from protobuf message wallet.UpdateO_Object
 */
export interface UpdateO_Object {
  /**
   * @generated from protobuf field: wallet.UpdateO_Object_Intern intern = 100;
   */
  intern?: UpdateO_Object_Intern;
  /**
   * @generated from protobuf field: wallet.UpdateO_Object_Public public = 200;
   */
  public?: UpdateO_Object_Public;
}
/**
 * @generated from protobuf message wallet.UpdateO_Object_Intern
 */
export interface UpdateO_Object_Intern {
  /**
   * addr contains lifecycle metadata for this wallet object.
   *
   * @generated from protobuf field: wallet.UpdateO_Object_Intern_Addr addr = 100;
   */
  addr?: UpdateO_Object_Intern_Addr;
  /**
   * labl contains lifecycle metadata for this wallet object.
   *
   * @generated from protobuf field: wallet.UpdateO_Object_Intern_Labl labl = 200;
   */
  labl?: UpdateO_Object_Intern_Labl;
  /**
   * stts is the resource status upon successful wallet modification.
   *
   * @generated from protobuf field: string stts = 300;
   */
  stts: string;
}
/**
 * @generated from protobuf message wallet.UpdateO_Object_Intern_Addr
 */
export interface UpdateO_Object_Intern_Addr {
  /**
   * Time is the unix timestamp in seconds of the most recent time at which this
   * wallet got re-validated by signing a message again.
   *
   * @generated from protobuf field: string time = 100;
   */
  time: string;
}
/**
 * @generated from protobuf message wallet.UpdateO_Object_Intern_Labl
 */
export interface UpdateO_Object_Intern_Labl {
  /**
   * Time is the unix timestamp in seconds of the most recent time at which the
   * wallet label got updated.
   *
   * @generated from protobuf field: string time = 100;
   */
  time: string;
}
/**
 * @generated from protobuf message wallet.UpdateO_Object_Public
 */
export interface UpdateO_Object_Public {}
declare class UpdateI$Type extends MessageType<UpdateI> {
  constructor();
  create(value?: PartialMessage<UpdateI>): UpdateI;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateI,
  ): UpdateI;
  internalBinaryWrite(
    message: UpdateI,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateI
 */
export declare const UpdateI: UpdateI$Type;
declare class UpdateI_Filter$Type extends MessageType<UpdateI_Filter> {
  constructor();
  create(value?: PartialMessage<UpdateI_Filter>): UpdateI_Filter;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateI_Filter,
  ): UpdateI_Filter;
  internalBinaryWrite(
    message: UpdateI_Filter,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateI_Filter
 */
export declare const UpdateI_Filter: UpdateI_Filter$Type;
declare class UpdateI_Object$Type extends MessageType<UpdateI_Object> {
  constructor();
  create(value?: PartialMessage<UpdateI_Object>): UpdateI_Object;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateI_Object,
  ): UpdateI_Object;
  internalBinaryWrite(
    message: UpdateI_Object,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateI_Object
 */
export declare const UpdateI_Object: UpdateI_Object$Type;
declare class UpdateI_Object_Intern$Type extends MessageType<UpdateI_Object_Intern> {
  constructor();
  create(value?: PartialMessage<UpdateI_Object_Intern>): UpdateI_Object_Intern;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateI_Object_Intern,
  ): UpdateI_Object_Intern;
  internalBinaryWrite(
    message: UpdateI_Object_Intern,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateI_Object_Intern
 */
export declare const UpdateI_Object_Intern: UpdateI_Object_Intern$Type;
declare class UpdateI_Object_Public$Type extends MessageType<UpdateI_Object_Public> {
  constructor();
  create(value?: PartialMessage<UpdateI_Object_Public>): UpdateI_Object_Public;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateI_Object_Public,
  ): UpdateI_Object_Public;
  internalBinaryWrite(
    message: UpdateI_Object_Public,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateI_Object_Public
 */
export declare const UpdateI_Object_Public: UpdateI_Object_Public$Type;
declare class UpdateI_Object_Symbol$Type extends MessageType<UpdateI_Object_Symbol> {
  constructor();
  create(value?: PartialMessage<UpdateI_Object_Symbol>): UpdateI_Object_Symbol;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateI_Object_Symbol,
  ): UpdateI_Object_Symbol;
  internalBinaryWrite(
    message: UpdateI_Object_Symbol,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateI_Object_Symbol
 */
export declare const UpdateI_Object_Symbol: UpdateI_Object_Symbol$Type;
declare class UpdateI_Object_Update$Type extends MessageType<UpdateI_Object_Update> {
  constructor();
  create(value?: PartialMessage<UpdateI_Object_Update>): UpdateI_Object_Update;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateI_Object_Update,
  ): UpdateI_Object_Update;
  internalBinaryWrite(
    message: UpdateI_Object_Update,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateI_Object_Update
 */
export declare const UpdateI_Object_Update: UpdateI_Object_Update$Type;
declare class UpdateO$Type extends MessageType<UpdateO> {
  constructor();
  create(value?: PartialMessage<UpdateO>): UpdateO;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateO,
  ): UpdateO;
  internalBinaryWrite(
    message: UpdateO,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateO
 */
export declare const UpdateO: UpdateO$Type;
declare class UpdateO_Filter$Type extends MessageType<UpdateO_Filter> {
  constructor();
  create(value?: PartialMessage<UpdateO_Filter>): UpdateO_Filter;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateO_Filter,
  ): UpdateO_Filter;
  internalBinaryWrite(
    message: UpdateO_Filter,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateO_Filter
 */
export declare const UpdateO_Filter: UpdateO_Filter$Type;
declare class UpdateO_Object$Type extends MessageType<UpdateO_Object> {
  constructor();
  create(value?: PartialMessage<UpdateO_Object>): UpdateO_Object;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateO_Object,
  ): UpdateO_Object;
  internalBinaryWrite(
    message: UpdateO_Object,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateO_Object
 */
export declare const UpdateO_Object: UpdateO_Object$Type;
declare class UpdateO_Object_Intern$Type extends MessageType<UpdateO_Object_Intern> {
  constructor();
  create(value?: PartialMessage<UpdateO_Object_Intern>): UpdateO_Object_Intern;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateO_Object_Intern,
  ): UpdateO_Object_Intern;
  internalBinaryWrite(
    message: UpdateO_Object_Intern,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateO_Object_Intern
 */
export declare const UpdateO_Object_Intern: UpdateO_Object_Intern$Type;
declare class UpdateO_Object_Intern_Addr$Type extends MessageType<UpdateO_Object_Intern_Addr> {
  constructor();
  create(
    value?: PartialMessage<UpdateO_Object_Intern_Addr>,
  ): UpdateO_Object_Intern_Addr;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateO_Object_Intern_Addr,
  ): UpdateO_Object_Intern_Addr;
  internalBinaryWrite(
    message: UpdateO_Object_Intern_Addr,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateO_Object_Intern_Addr
 */
export declare const UpdateO_Object_Intern_Addr: UpdateO_Object_Intern_Addr$Type;
declare class UpdateO_Object_Intern_Labl$Type extends MessageType<UpdateO_Object_Intern_Labl> {
  constructor();
  create(
    value?: PartialMessage<UpdateO_Object_Intern_Labl>,
  ): UpdateO_Object_Intern_Labl;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateO_Object_Intern_Labl,
  ): UpdateO_Object_Intern_Labl;
  internalBinaryWrite(
    message: UpdateO_Object_Intern_Labl,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateO_Object_Intern_Labl
 */
export declare const UpdateO_Object_Intern_Labl: UpdateO_Object_Intern_Labl$Type;
declare class UpdateO_Object_Public$Type extends MessageType<UpdateO_Object_Public> {
  constructor();
  create(value?: PartialMessage<UpdateO_Object_Public>): UpdateO_Object_Public;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: UpdateO_Object_Public,
  ): UpdateO_Object_Public;
  internalBinaryWrite(
    message: UpdateO_Object_Public,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message wallet.UpdateO_Object_Public
 */
export declare const UpdateO_Object_Public: UpdateO_Object_Public$Type;
export {};
